# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscription.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12subscription.proto\x12\x0csubscription\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x13SubscriptionRequest\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12.\n\nstart_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x06status\x18\x06 \x01(\x0e\x32\x14.subscription.Status\"\xd8\x01\n\x14SubscriptionResponse\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12.\n\nstart_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x06status\x18\x06 \x01(\x0e\x32\x14.subscription.Status*\"\n\x06Status\x12\n\n\x06\x41\x43TIVE\x10\x00\x12\x0c\n\x08INACTIVE\x10\x01\x32\x8d\x03\n\x13SubscriptionService\x12[\n\x12\x43reateSubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12[\n\x12\x44\x65leteSubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12[\n\x12ModifySubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12_\n\x16GetSubscriptionDetails\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscription_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=506
  _globals['_STATUS']._serialized_end=540
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=70
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=285
  _globals['_SUBSCRIPTIONRESPONSE']._serialized_start=288
  _globals['_SUBSCRIPTIONRESPONSE']._serialized_end=504
  _globals['_SUBSCRIPTIONSERVICE']._serialized_start=543
  _globals['_SUBSCRIPTIONSERVICE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
