# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/subscription.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/subscription.proto\x12\x0csubscription\"\x89\x01\n\x13SubscriptionRequest\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\"\x8a\x01\n\x14SubscriptionResponse\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12\x12\n\nstart_date\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t2\x8d\x03\n\x13SubscriptionService\x12[\n\x12\x43reateSubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12[\n\x12\x44\x65leteSubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12[\n\x12ModifySubscription\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponse\x12_\n\x16GetSubscriptionDetails\x12!.subscription.SubscriptionRequest\x1a\".subscription.SubscriptionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.subscription_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUBSCRIPTIONREQUEST']._serialized_start=44
  _globals['_SUBSCRIPTIONREQUEST']._serialized_end=181
  _globals['_SUBSCRIPTIONRESPONSE']._serialized_start=184
  _globals['_SUBSCRIPTIONRESPONSE']._serialized_end=322
  _globals['_SUBSCRIPTIONSERVICE']._serialized_start=325
  _globals['_SUBSCRIPTIONSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
